//
// Created by addo6544 on 2026/9/24.
//

#ifndef FROSTJNI_WRAPPER_GENERATORS_DEFINED
#define FROSTJNI_WRAPPER_GENERATORS_DEFINED


#define FROSTJNI_JAVATYPES_WRAPPER_CTOR_EX(name, parent) \
    FROSTJNI_JAVATYPES_WRAPPER(name) (const jobject objIn) noexcept : FROSTJNI_JAVATYPES_WRAPPER(parent)(objIn) {}\
    FROSTJNI_JAVATYPES_WRAPPER(name) (const JavaRefView& refView) noexcept : FROSTJNI_JAVATYPES_WRAPPER(parent)(refView) {}
#define FROSTJNI_JAVATYPES_WRAPPER_CTOR(name) FROSTJNI_JAVATYPES_WRAPPER_CTOR_EX(name, Object)

#define FROSTJNI_JAVATYPES_WRAPPER_IMPL(Name, Super) class FROSTJNI_JAVATYPES_WRAPPER(Name) : public FROSTJNI_JAVATYPES_WRAPPER(Super)
#define FROSTJNI_JAVATYPES_WRAPPER_FWD(Name) class FROSTJNI_JAVATYPES_WRAPPER(Name);


#endif // FROSTJNI_WRAPPER_GENERATORS_DEFINED

// #ifdef FROSTJNI_WRAPPER_GENERATORS_UNDEF
// #undef FROSTJNI_WRAPPER_CTOR_EX
// #undef FROSTJNI_WRAPPER_CTOR
// #undef FROSTJNI_JAVATYPES_WRAPPER_IMPL
// #undef FROSTJNI_JAVATYPES_WRAPPER_FWD
// #endif

